DEFAULT_SYSTEM_PROMPT = "You are a virtual assistant created by the open source community. You have access to a chat log that involves a user who can also access a few other tools. Respond using markdown."
DEFAULT_TEMPERATURE = 0.5

# These are AI generated questions to populate in the search bar
GPT_QUESTIONS = [
    "What is your purpose?",
    "Can you understand sarcasm?",
    "How do you learn from data?",
    "Can you create original stories?",
    "What is the meaning of life?",
    "Can you translate languages?",
    "What is the most popular language?",
    "Can you recognize emotions?",
    "Can you write poetry?",
    "What is the difference between AI and ML?",
    "Can you summarize long texts?",
    "What is the most common language mistake?",
    "Can you understand humor?",
    "What is the best way to learn a language?",
    "Can you speak in different accents?",
    "What is the most widely spoken language?",
    "Can you understand idioms?",
    "Can you create jokes?",
    "What is the difference between a language model and a chatbot?",
    "Can you recognize names and faces?",
    "What is the most difficult language to learn?",
    "Can you understand figurative language?",
    "Can you create dialogues?",
    "What is the most common language learning mistake?",
    "Can you understand cultural references?",
    "Can you write songs?",
    "What is the best language learning app?",
    "Can you recognize and respond to voice commands?",
    "What is the most popular language learning method?",
    "Can you understand and respond to emotions?",
    "Can you create debates?",
    "What is the difference between a language model and a translator?",
    "Can you recognize and respond to gestures?",
    "What is the most difficult accent to understand?",
    "Can you understand and respond to tone?",
    "Can you create speeches?",
    "What is the best way to practice a language?",
    "Can you recognize and respond to facial expressions?",
    "What is the most popular language exchange platform?",
    "Can you understand and respond to irony?",
    "Can you create presentations?",
    "What is the difference between a language model and a language teacher?",
    "Can you recognize and respond to body language?",
    "What is the most common language teaching method?",
    "Can you understand and respond to rhetorical questions?",
    "Can you create news articles?",
    "What is the best way to learn vocabulary?",
    "Can you recognize and respond to persuasive language?",
    "What is the most popular language learning podcast?",
    "Can you understand and respond to slang?",
    "Can you create academic papers?",
    "What is the difference between a language model and a language exchange partner?",
    "Can you recognize and respond to implied meaning?",
    "What is the most difficult language to translate?",
    "Can you understand and respond to allusions?",
    "Can you create social media posts?",
    "What is the best way to learn grammar?",
    "Can you recognize and respond to hyperbole?",
    "What is the most popular language learning YouTube channel?",
    "Can you understand and respond to onomatopoeias?",
    "Can you create product descriptions?",
    "What is the difference between a language model and a language assessment tool?",
    "Can you recognize and respond to euphemisms?",
    "What is the most common language learning goal?",
    "Can you understand and respond to oxymorons?",
    "Can you create marketing copy?",
    "What is the best way to practice pronunciation?",
    "Can you recognize and respond to anachronisms?",
    "What is the most popular language learning blog?",
    "Can you understand and respond to malapropisms?",
    "Can you create technical writing?",
    "What is the difference between a language model and a language processing tool?",
    "Can you recognize and respond to neologisms?",
    "What is the most difficult language to speak?",
    "Can you understand and respond to clichés?",
    "Can you create instructional materials?",
    "What is the best way to learn phrases?",
    "Can you recognize and respond to solecisms?",
    "What is the most popular language learning app for kids?",
    "Can you understand and respond to proverbs?",
    "Can you create social media content?",
    "What is the difference between a language model and a language generation tool?",
    "Can you recognize and respond to double meanings?",
    "What is the most common language learning obstacle?",
    "Can you understand and respond to ambiguity?",
    "Can you create educational content?",
    "What is the best way to learn idioms?",
    "Can you recognize and respond to connotations?",
    "What is the most popular language learning platform?",
    "Can you understand and respond to denotations?",
    "Can you create children's books?",
    "What is the difference between a language model and a language understanding tool?",
    "Can you recognize and respond to slang terms?",
    "What is the most difficult language to read?",
    "Can you understand and respond to colloquialisms?",
    "Can you create video scripts?",
    "What is the best way to practice listening?",
    "Can you recognize and respond to regional dialects?",
    "What is the most popular language learning community?",
    "Can you understand and respond to ambiguous words?",
    "Can you create press releases?",
    "What is the difference between a language model and a language analysis tool?",
    "Can you recognize and respond to dialects?",
    "What is the most common language learning motivation?",
    "Can you understand and respond to figurative language?",
    "Can you create email newsletters?",
    "What is the best way to learn phrases?",
    "Can you recognize and respond to cultural references?",
    "What is the most popular language learning software?",
    "Can you understand and respond to humor?",
    "Can you create landing pages?",
    "What is the difference between a language model and a language teaching tool?",
    "Can you recognize and respond to irony?",
    "What is the most difficult language to write?",
    "Can you understand and respond to allusions?",
    "Can you create blog posts?",
    "What is the best way to practice speaking?",
    "Can you recognize and respond to euphemisms?",
    "What is the most popular language learning course?",
    "Can you understand and respond to oxymorons?",
    "Can you create sales pages?",
    "What is the difference between a language model and a language testing tool?",
    "Can you recognize and respond to anachronisms?",
    "What is the most common language learning challenge?",
    "Can you understand and respond to malapropisms?",
    "Can you create website content?",
    "What is the best way to learn vocabulary?",
    "Can you recognize and respond to neologisms?",
    "What is the most popular language learning resource?",
    "Can you understand and respond to clichés?",
    "Can you create mobile app content?",
    "What is the difference between a language model and a language evaluation tool?",
    "Can you recognize and respond to solecisms?",
    "What is the most difficult language to understand?"
]